### ISSUE TITLE
Latest `publish` jobs failed

### ISSUE THREAD

**Issue by vic1707** [mattpocock/ts-reset#198]
I wanted to take advantage of the new `promise-catch` patch released 2 months ago but it wasn't published on NPM because the job failed on a `pnpm-lock.yaml` error.

https://github.com/total-typescript/ts-reset/actions/runs/9267912383

**Comment by mattpocock** [comment]
Apologies for the delay, will fix today

**Comment by vic1707** [comment]
No problem thank you for all your work 🥰
