### ISSUE TITLE
Feature idea: Change Map from any --> unknown

### ISSUE THREAD

**Issue by Zamiell** [mattpocock/ts-reset#41]
Both of the default generic parameters of `Map` are `any`.
You should change them to `unknown` for the same reasons that you e.g. change `JSON.parse`.

For a more in-depth discussion on this, see: https://github.com/microsoft/TypeScript/issues/52552

**Comment by m10rten** [comment]
Maps already have a generic option: `Map<K, T>()` where as JSON.parse does not, I think the goal is to improve existing features and not add generics everywhere, that said, if you do not set the `K & T` it will be any.

Up for debate, it is safer, but you can also just add a starting generic.

**Comment by Zamiell** [comment]
I'm aware that maps have a generic option. The point of this issue is that sometimes programmers forget to specify the generic parameter, so the default generic parameter is used, which means that `any` is slipped into the codebase, which should be solved at the type-level.

**Comment by mattpocock** [comment]
Agree, this issue deserves to stay open! My response is on the [PR](https://github.com/total-typescript/ts-reset/pull/53#issuecomment-1440140259)

**Comment by nmay231** [comment]
FYI, the title should be "any --> unknown" :slightly_smiling_face:

**Comment by Crisfole** [comment]
Ultimately this is just about the _default_ value, so `Map<K = unknown, V = unknown>` right?

**Comment by Zamiell** [comment]
yes

**Comment by arnorhs** [comment]
So, what is the status of the PR?

Seems like the test is accurate - I had the same defined myself in a big repo at work, and it has not caused any issues - i suggest this ends up being merged.

**Comment by amitdahan** [comment]
Seems this issue was closed in #53 ?

**Comment by mattpocock** [comment]
Correct, closed by #53
